---
# Pulse Meter Sensor - Water
#
# The pulse meter sensor allows you to count the number and frequency of pulses
# on any pin.
#
# This one is attached to my Water meter, and sends a pulse for each L of water
# used.
#
# https://esphome.io/components/sensor/pulse_meter.html
#
platform: pm1006
id: sensor_c02
pm_2_5:
  name: "${name} PM2.5 Concentration"
  icon: "mdi:molecule-co2"

