---
# Generic ESP8285 module
#
# Can be found in various Tuya-based devices.
#
# https://docs.platformio.org/en/latest/boards/espressif8266/esp8285.html
#
esphome:
  <<: !include .esphome.yaml
  platform: ESP8266
  board: esp8285

  # uncomment this to change the OTA password between firmware updates
  # on_boot:
  #   - lambda: |-
  #       id(component_ota).set_auth_password("${ota_password}");  
