language: python
python:
- "3.9"
before_install:
- mv travis_secrets.yaml secrets.yaml
- sudo apt-get install -y libudev-dev
install:
- pip3 install homeassistant
  - git clone https://github.com/heyajohnny/afvalinfo.git afvalinfo_component/
  - mv afvalinfo_component/custom_components config/custom_components
script:
- hass -c . --script check_config