- id: '1614892098467'
  alias: Home Assistant update notification
  description: ''
  use_blueprint:
    path: Klumper/update_notification.yaml
    input:
      notification_message: Home Assistant {{ newest_version }} is available
      delay: 0
      updater: binary_sensor.updater
      notification_title: HASS update ready
      notify_device: 24426efdfe135d6d9244b25d13739ca5
      is_ios: false
- id: '1615978879105'
  alias: Afval herinnering fam
  description: ''
  use_blueprint:
    path: westenberg/garbage-reminder.yaml
    input:
      day_offset: '1'
      reminder_time: '19:00:00'
      reminder_title: Afval herinnering 🗑️🚮
      reminder_message: 'Morgen wordt opgehaald:  '
      garbage_sensor_1: sensor.gft
      garbage_sensor_2: sensor.pmd
      garbage_sensor_3: sensor.papier
      garbage_sensor_4: sensor.restafval
      notifier: notify.family_phones
- id: unavailable_entities_notification
  alias: Unavailable Entities Notification
  description: Create persistent notification if there are unavailable entities, dismiss
    if none.
  mode: restart
  trigger:
  - platform: state
    entity_id: sensor.unavailable_entities
  action:
  - choose:
      conditions:
      - condition: numeric_state
        entity_id: sensor.unavailable_entities
        below: 1
      sequence:
      - service: persistent_notification.dismiss
        data:
          notification_id: unavailable_entities
    default:
    - service: persistent_notification.create
      data:
        title: Unavailable Entities
        message: '- {{ expand(state_attr(''sensor.unavailable_entities'',''entities''))|map(attribute=''entity_id'')|join(''

          - '') }}'
        notification_id: unavailable_entities
- id: '1635608563987'
  alias: ZHA - Philips Hue Dimmer Switch Kamer Stefan
  description: ''
  use_blueprint:
    path: vanstinator/zha-philips-hue-dimmer-switch-rwl020-rwl021.yaml
    input:
      remote: 0e31c0fce49bb254ebfa1cd927f71017
      brightness: 70
      light:
        entity_id:
        - light.kamer_stefan_leeslamp
        - light.kamer_stefan_lamp
        - light.kamer_stefan_bureaulamp
      force_brightness: true
- id: '1635619715991'
  alias: ZHA - Philips Hue Dimmer Switch Keuken
  description: ''
  use_blueprint:
    path: vanstinator/zha-philips-hue-dimmer-switch-rwl020-rwl021.yaml
    input:
      remote: bee3e75754cde7880141e304e1035169
      brightness: 40
      force_brightness: true
      light:
        area_id:
        - achterdeur
        - 283dbabf623d4e009860c39890fdc8e9
        - fe7b5b313f884c66812a4b7b3fb1f162
- id: '1635630838683'
  alias: Motion sensor lamp gang
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.gang_beweging_sensor
    id: motion_on
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.gang_beweging_sensor
    id: motion_off
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: motion_on
      - condition: or
        conditions:
        - condition: state
          entity_id: sun.sun
          state: below_horizon
        - condition: numeric_state
          entity_id: sensor.gang_beweging_sensor_lux
          below: '5'
      sequence:
      - type: turn_on
        device_id: d84a8f705175b8cdb9ec708122336b6c
        entity_id: light.gang_lamp
        domain: light
        brightness_pct: 60
    - conditions:
      - condition: trigger
        id: motion_off
      sequence:
      - type: turn_off
        device_id: d84a8f705175b8cdb9ec708122336b6c
        entity_id: light.gang_lamp
        domain: light
    default: []
  mode: restart
- id: '1635874279845'
  alias: Low battery level detection & notification for all battery sensors
  description: ''
  use_blueprint:
    path: tykeal/low-battery.yaml
    input:
      actions:
      - service: notify.mobile_app_mobiel_stefan
        data:
          title: Batterij laag! 🔋
          message: 'Batterij is laag voor: {{sensors}}'
      exclude:
        entity_id: []
        device_id:
        - 77c85b50e9a433ee4e281cb1d8ffd178
        - 7d65adcd43584595a568550bd4894e87
        - 7f43d99feb035376afb28284dfd44743
        - 24426efdfe135d6d9244b25d13739ca5
        - 4915d4c39c644da99989890b4c95786e
- id: '1642976109058'
  alias: Deurbel app/licht notificatie
  description: Deurbel app/licht notificatie
  trigger:
  - platform: state
    entity_id: binary_sensor.doorbell_sensor_vibration_sensor
    from: 'off'
    to: 'on'
  condition:
  - condition: zone
    entity_id: device_tracker.mobiel_stefan
    zone: zone.home
  action:
  - service: notify.mobile_app_mobiel_stefan
    data:
      message: De bel gaat!
      title: Bel! 🔔🔔🔔
  - service: script.test123
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  mode: single
- id: '1644356794224'
  alias: HA shutdown
  description: ''
  trigger:
  - platform: homeassistant
    event: shutdown
    id: shutdown
  - platform: homeassistant
    event: start
    id: start
  condition: []
  action:
  - service: notify.mobile_app_mobiel_stefan
    data:
      message: Yes/No
      title: Please select one
      data:
        actions:
        - action: SEND_YES
          title: Yes!
        - action: SEND_NO
          title: No!
  mode: single
- id: '1646153872084'
  alias: 3D print finish
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.octoprint_printing
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 3
      seconds: 0
  condition: []
  action:
  - service: notify.mobile_app_mobiel_stefan
    data:
      message: 3D printer has finished. Shut down printer?
      title: '3D print finished! '
      data:
        actions:
        - action: TURN_OFF_PRINTER
          title: SHUT DOWN NOW
        - action: DO_NOTHING
          title: DO NOTHING
  - wait_for_trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: TURN_OFF_PRINTER
      context:
        user_id:
        - f1ad3343d187403d8a6f51670cf705b6
      id: turn off
    continue_on_timeout: false
    timeout: 01:00:00
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.attic_3d_printer
  mode: single
- id: '1646247786443'
  alias: Washing machine notification
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.washer_status
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition: []
  action:
  - service: notify.family_phones
    data:
      message: Wasmachine is klaar met het programma.
      title: Wasmachine is klaar 🧺✔️
  mode: single
- id: '1646400163104'
  alias: Papa leaves work notification
  description: When papa leaves work towards home a notification should be send to
    family phones.
  trigger:
  - platform: state
    entity_id: proximity.work_papa
    attribute: dir_of_travel
    to: away_from
    for:
      hours: 0
      minutes: 0
      seconds: 20
  condition:
  - condition: state
    entity_id: proximity.home_papa
    attribute: dir_of_travel
    state: towards
    for:
      hours: 0
      minutes: 0
      seconds: 20
  action:
  - service: notify.mobile_app_mobiel_stefan # notify.family_phones
    data_template:
      message: Geschatte aankomst om {{ eta }}.
      title: Papa is op weg naar huis! 👨➡️🏠
  variables:
    eta: '{{ (now() + timedelta(minutes=states(''sensor.work_p_dynamic'') | float(0))).strftime(''%H:%M'')
      }}'
  mode: single
- id: '1646401163114'
  alias: Mama leaves work notification
  description: When mama leaves work towards home a notification should be send to
    family phones.
  trigger:
  - platform: state
    entity_id: proximity.work_mama
    attribute: dir_of_travel
    to: away_from
    for:
      hours: 0
      minutes: 0
      seconds: 20
  condition:
  - condition: state
    entity_id: proximity.home_mama
    attribute: dir_of_travel
    state: towards
    for:
      hours: 0
      minutes: 0
      seconds: 20
  action:
  - service: notify.mobile_app_mobiel_stefan # notify.family_phones
    data_template:
      message: Geschatte aankomst om {{ eta }}.
      title: Mama is op weg naar huis! 👩➡️🏠
  variables:
    eta: '{{ (now() + timedelta(minutes=states(''sensor.work_m_dynamic'') | float(0))).strftime(''%H:%M'')
      }}'

