- alias: Motion Sensor Lights On
  trigger:
    platform: state
    entity_id: binary_sensor.voordeur_sensor
  condition:
    condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
    service: homeassistant.turn_on
    entity_id: light.lamp_voordeur
    data:
      transition: 1
      brightness: 200
      color_name: wheat
  id: 7db7f9c4ffe145f7afbf804e0c523344
- id: '1592952081853'
  alias: Turn on light when kitchen switch is pressed
  description: ''
  trigger:
  - device_id: 244e64ce923a46e986c183f5923b01e5
    domain: hue
    platform: device
    subtype: turn_on
    type: remote_button_short_release
  condition: []
  action:
  - device_id: 50024ea994de40a0a9d153b25a061783
    domain: switch
    entity_id: switch.switch
    type: turn_on
- id: '1592952171677'
  alias: Turn off light when kitchen swith is pressed
  description: ''
  trigger:
  - device_id: 244e64ce923a46e986c183f5923b01e5
    domain: hue
    platform: device
    subtype: turn_off
    type: remote_button_short_release
  condition: []
  action:
  - device_id: 50024ea994de40a0a9d153b25a061783
    domain: switch
    entity_id: switch.switch
    type: turn_off
- id: '1614892098467'
  alias: Home Assistant update notification
  description: ''
  use_blueprint:
    path: Klumper/update_notification.yaml
    input:
      notification_message: Home Assistant {{ newest_version }} is available
      delay: 0
      updater: binary_sensor.updater
      notification_title: HASS update ready
      notify_device: 3ef48af6fd8a5c6c11667cab8de3f540
      is_ios: false
- id: '1615978879105'
  alias: Garbage reminder stefan
  description: ''
  use_blueprint:
    path: westenberg/garbage-reminder.yaml
    input:
      day_offset: '1'
      reminder_time: '10:00:00'
      reminder_title: Afval herinnering
      reminder_message: 'Morgen wordt opgehaald:  '
      notifier: notify.mobile_app_oneplus_a5000
      garbage_sensor_1: sensor.afvalinfo_papier_ymd
      garbage_sensor_2: sensor.afvalinfo_pbd_ymd
      garbage_sensor_3: sensor.afvalinfo_restafval_ymd
      garbage_sensor_4: sensor.afvalinfo_gft_ymd
- id: '1615979101691'
  alias: Garbage reminder mama
  description: ''
  use_blueprint:
    path: westenberg/garbage-reminder.yaml
    input:
      day_offset: '1'
      reminder_time: '10:00:00'
      reminder_title: Afval herinnering
      reminder_message: 'Morgen wordt opgehaald:'
      notifier: notify.mobile_app_sm_a520f
      garbage_sensor_1: sensor.afvalinfo_gft_ymd
      garbage_sensor_2: sensor.afvalinfo_papier_ymd
      garbage_sensor_3: sensor.afvalinfo_pbd_ymd
      garbage_sensor_4: sensor.afvalinfo_restafval_ymd
