- alias: Motion Sensor Lights On
  trigger:
    platform: state
    entity_id: binary_sensor.voordeur_sensor
  condition:
    condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
    service: homeassistant.turn_on
    entity_id: light.lamp_voordeur
    data:
      transition: 1
      brightness: 200
      color_name: wheat
  id: 7db7f9c4ffe145f7afbf804e0c523344
- id: '1592952081853'
  alias: Turn on light when kitchen switch is pressed
  description: ''
  trigger:
  - device_id: 244e64ce923a46e986c183f5923b01e5
    domain: hue
    platform: device
    subtype: turn_on
    type: remote_button_short_release
  condition: []
  action:
  - type: turn_on
    device_id: f78a9982007c96ad1a67292e8199accd
    entity_id: switch.bw_shp10_1
    domain: switch
  mode: single
- id: '1592952171677'
  alias: Turn off light when kitchen swith is pressed
  description: ''
  trigger:
  - device_id: 244e64ce923a46e986c183f5923b01e5
    domain: hue
    platform: device
    subtype: turn_off
    type: remote_button_short_release
  condition: []
  action:
  - type: turn_off
    device_id: f78a9982007c96ad1a67292e8199accd
    entity_id: switch.bw_shp10_1
    domain: switch
  mode: single
- id: '1614892098467'
  alias: Home Assistant update notification
  description: ''
  use_blueprint:
    path: Klumper/update_notification.yaml
    input:
      notification_message: Home Assistant {{ newest_version }} is available
      delay: 0
      updater: binary_sensor.updater
      notification_title: HASS update ready
      notify_device: 24426efdfe135d6d9244b25d13739ca5
      is_ios: false
- id: '1615978879105'
  alias: Garbage reminder stefan
  description: ''
  use_blueprint:
    path: westenberg/garbage-reminder.yaml
    input:
      day_offset: '1'
      reminder_time: '10:00:00'
      reminder_title: Afval herinnering
      reminder_message: 'Morgen wordt opgehaald:  '
      notifier: notify.mobi
      garbage_sensor_1: sensor.afvalinfo_papier_ymd
      garbage_sensor_2: sensor.afvalinfo_pbd_ymd
      garbage_sensor_3: sensor.afvalinfo_restafval_ymd
      garbage_sensor_4: sensor.afvalinfo_gft_ymd
- id: '1615979101691'
  alias: Garbage reminder mama
  description: ''
  use_blueprint:
    path: westenberg/garbage-reminder.yaml
    input:
      day_offset: '1'
      reminder_time: '10:00:00'
      reminder_title: Afval herinnering
      reminder_message: 'Morgen wordt opgehaald: '
      notifier: notify.mobile_app_sm_a520f
      garbage_sensor_1: sensor.afvalinfo_gft_ymd
      garbage_sensor_2: sensor.afvalinfo_papier_ymd
      garbage_sensor_3: sensor.afvalinfo_pbd_ymd
      garbage_sensor_4: sensor.afvalinfo_restafval_ymd
- id: unavailable_entities_notification
  alias: Unavailable Entities Notification
  description: Create persistent notification if there are unavailable entities, dismiss
    if none.
  mode: restart
  trigger:
  - platform: state
    entity_id: sensor.unavailable_entities
  action:
  - choose:
      conditions:
      - condition: numeric_state
        entity_id: sensor.unavailable_entities
        below: 1
      sequence:
      - service: persistent_notification.dismiss
        data:
          notification_id: unavailable_entities
    default:
    - service: persistent_notification.create
      data:
        title: Unavailable Entities
        message: '- {{ expand(state_attr(''sensor.unavailable_entities'',''entities''))|map(attribute=''entity_id'')|join(''

          - '') }}'
        notification_id: unavailable_entities
 