# sleep sensor
- platform: template
  sensors:
    stefan_slaapt:
      value_template: >-
        {{ is_state('sensor.mobiel_stefan_battery_state','charging')
        and is_state('device_tracker.mobiel_stefan','home')
        and is_state('light.kamer_stefan','off') }}

# binary sensor icon test
- platform: template
  sensors:
    mobiel_stefan_bluetooth_state_test:
      value_template: "{{ states('binary_sensor.mobiel_stefan_bluetooth_state') }}"
      icon_template: >-
        {% if is_state("binary_sensor.mobiel_stefan_bluetooth_state", "on") %}
          mdi:email-alert-outline
        {% else %}
          mdi:email-remove-outline
        {% endif %}

# washing machine status on/off
- platform: template
  sensors:
    washer_status:
      friendly_name: "Washing Machine status"
      delay_on:
        minutes: 2
      delay_off:
        minutes: 6
      value_template: >-
        {{ states('sensor.washing_machine_power')|float > 3 }}

# TV status on/off
- platform: template
  sensors:
    tv_status:
      friendly_name: "TV status"
      delay_on:
        minutes: 1
      delay_off:
        minutes: 1
      value_template: >-
        {{ states('sensor.samsung_tv_power')|float > 30 }}

# day/night
- platform: tod
  name: Night
  after: sunset
  before: sunrise
