# octopi
- platform: mjpeg
  name: OctoPrint
  still_image_url: http://192.168.50.118/webcam/?action=snapshot
  mjpeg_url: http://192.168.50.118/webcam/?action=stream

# Octoprint Preview
- platform: generic
  name: OctoPrint Preview
  still_image_url: "http://192.168.50.118/plugin/UltimakerFormatPackage/thumbnail/{{ states('sensor.octoprint_current_filename') |regex_replace(find='gcode', replace='png', ignorecase=True)}}"
  scan_interval: 5
  content_type: image/png