# ########################################
# ###             GENERAL              ###
# ########################################
homeassistant:
  name: Home
  latitude: !secret lat_coord
  longitude: !secret long_coord
  elevation: 0
  unit_system: metric
  time_zone: !secret time_zone
  customize: !include customize.yaml

config:
hassio:
system_health:
ssdp:
zeroconf:
discovery:
cloud:
my:
energy:

# to fix custom cards in home assistant cast
http:
  cors_allowed_origins:
    - https://cast.home-assistant.io

# ########################################
# ###             MOBILE               ###
# ########################################
mobile_app:

# ########################################
# ###                GUI               ###
# ########################################
lovelace:
  mode: yaml

  # Additional resources
  resources: !include lovelace/resources.yaml

  # Lovelace dashboards
  dashboards:
    lovelace-default: # Needs to contain a hyphen (-)
      mode: yaml
      filename: lovelace_default.yaml
      title: Default
      icon: mdi:tools
      show_in_sidebar: true

map:

frontend:
  themes: !include_dir_merge_named themes

# ########################################
# ###              LOGGING             ###
# ########################################

recorder: !include logging/recorder.yaml
history: !include logging/history.yaml
logbook: !include logging/logbook.yaml
logger: !include logging/logger.yaml

# ########################################
# ###              ENTITIES            ###
# ########################################
person:

# ########################################
# ###             SERVICES             ###
# ########################################
sun:
shopping_list:
notify: !include notify.yaml

#python_script:

tts:
  - platform: google_translate

# ########################################
# ###          INTEGRATIONS            ###
# ########################################

shell_command: !include shell.yaml

# influxdb
influxdb:
  host: 192.168.50.11

# utility meter
utility_meter: !include utility_meter.yaml

# proximity 
proximity: !include proximity.yaml

# ########################################
# ###          PLATFORMS               ###
# ########################################
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
# script:
scene: !include scenes.yaml
sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
light: !include light.yaml
input_select: !include input_select.yaml
