# keuken
- platform: group
  name: Keuken tafel
  entities:
    - light.keuken_lamp_1
    - light.keuken_lamp_2
    - light.keuken_lamp_3
    - light.keuken_lamp_4

# kamer stefan
- platform: group
  name: Kamer stefan
  entities:
    - light.kamer_stefan_bureaulamp
    - light.kamer_stefan_lamp
    - light.kamer_stefan_leeslamp

