## Basic desktop UI
---
button_card_templates: !include_dir_merge_named "custom_components/ui_lovelace_minimalist/__ui_minimalist__/ulm_templates/"

title: Basic UI
# theme: "minimalist-desktop"
background: "var(--background-image)"
views: !include_dir_list lovelace/dashboards/lovelace_improve