---
# Wi-Fi component package
#
# Contains my common Wi-Fi setup.
#
# https://esphome.io/components/wifi.html
#
substitutions:
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  wifi_backup_ssid: !secret wifi_backup_ssid
  wifi_backup_password: !secret wifi_backup_password
  wifi_ap_password: "esphome-${slug}"
  gateway: !secret gateway
  subnet: !secret subnet

wifi:
  id: component_wifi
  networks:
    - ssid: "${wifi_ssid}"
      password: "${wifi_password}"
    - ssid: "${wifi_backup_ssid}"
      password: "${wifi_backup_password}"
  reboot_timeout: 10min
  ap:
    ssid: "${name}"
    password: "${wifi_ap_password}"
  manual_ip:
    static_ip: ${static_ip}
    gateway: ${gateway}
    subnet: ${subnet}

sensor:
  - <<: !include ../sensors/wifi_signal_percentage.yaml
  - <<: !include ../sensors/wifi_signal.yaml
    on_value:
      - component.update: sensor_wifi_signal_percentage

text_sensor:
  - <<: !include ../text_sensors/wifi_info.yaml
