---
    # Airco buiten
    #
    # See: https://github.com/ginkage/MHI-AC-Ctrl-ESPHome 
    #
    substitutions:
      label: ac
      slug: ac-buiten
      deviceid: ac_buiten
      name: Airco buiten
      description: Monitors and controls the mitsubishi AC outside.
      api_password: !secret esphome_ac_buiten_api_password
      ota_password: !secret esphome_ac_buiten_ota_password
      static_ip: !secret esphome_ac_buiten_static_ip
    
    packages:
      device: !include devices/mitsubishi_airco.yaml