---
# Airco kamer PM
#
# See: https://github.com/ginkage/MHI-AC-Ctrl-ESPHome 
#
substitutions:
  label: ac
  slug: ac-kamer-pm
  deviceid: ac_kamer_pm
  name: Airco kamer pm
  description: Monitors and controls the mitsubishi AC kamer pm.
  ota_password: !secret esphome_kamer_pm_ota_password
  static_ip: !secret esphome_kamer_pm_static_ip

packages:
  device: !include devices/mitsubishi_airco.yaml