---
# AC Stefan
#
# Monitors the power used by the AC in Stefan's room.
#
substitutions:
  label: esp09
  slug: ac-stefan
  name: AC Stefan
  description: Monitors power used by Stefan's AC.
  ota_password: !secret esphome_ac_stefan_ota_password
  static_ip: !secret esphome_ac_stefan_static_ip

packages:
  device: !include devices/gosund_sp1.yaml