---
# Ceiling fan
#
# Controls the ceiling fan in the living room. Speed 3 has been turned off for safety.
#
substitutions:
  label: none
  slug: ceiling-fan
  name: Ceiling Fan
  description: Controls the ceiling fan in the living room.
  api_password: !secret esphome_ceiling_fan_api_password
  ota_password: !secret esphome_ceiling_fan_ota_password
  static_ip: !secret esphome_ceiling_fan_static_ip

packages:
  device: !include devices/ifan02.yaml