
---
#
# Device: Doorbell sensor
#
# Uses simple vibration sensor
#
#
substitutions:
  label: none
  slug: doorbell-sensor
  name: Doorbell sensor
  description: Detects vibration when the doorbell is ringing.
  ota_password: !secret esphome_doorbell_sensor_ota_password
  static_ip: !secret esphome_doorbell_sensor_static_ip

packages:
  device: !include devices/vibration_sensor.yaml