---
# Heater Stefan
#
# Monitors the power used by the heater in Stefan's room.
#
substitutions:
  label: none
  slug: heater-stefan
  name: Heater Stefan
  description: Monitors power used by Stefan's heater.
  ota_password: !secret esphome_heater_stefan_ota_password
  static_ip: !secret esphome_heater_stefan_static_ip

packages:
  device: !include devices/blitzwolf_shp10.yaml