---
# PC Stefan
#
# Monitors the power used by the Stefan's PC
#
substitutions:
  label: none
  slug: pc-stefan
  name: PC Stefan
  description: Monitors power used by Stefan's PC.
  ota_password: !secret esphome_pc_stefan_ota_password
  static_ip: !secret esphome_pc_stefan_static_ip

packages:
  device: !include devices/blitzwolf_shp10_no_button.yaml