---
# 
# Vindriktning Livingroom
#
# Monitors the airquality in the living room. 
#
substitutions:
  label: none
  slug: vindriktning-livingroom
  name: Vindriktning Livingroom
  description: Monitors airquality (PM2.5) in the livingroom.
  api_password: !secret esphome_vindr_livingroom_api_password
  ota_password: !secret esphome_vindr_livingroom_ota_password
  static_ip: !secret esphome_vindr_livingroom_static_ip

packages:
  device: !include devices/ikea_vindriktning.yaml